package config

const (
	PLAYER_BASE_HEALTH = 100
	PLAYER_MAX_SPEED   = 220.0
	RESPAWN_DELAY      = 5

	PLAYER_COLLISION_RADIUS = 16.0
	PLAYER_VISION_RADIUS    = 180.0
	PLAYER_VISION_CONE      = 420.0
)
