package config

const (
	DEFAULT_SIDEARM_DAMAGE    = 20
	DEFAULT_SIDEARM_FIRE_RATE = 4.0
	DEFAULT_SIDEARM_RANGE     = 520.0
	DEFAULT_SIDEARM_AMMO      = 12

	DEFAULT_PRIMARY_DAMAGE    = 28
	DEFAULT_PRIMARY_FIRE_RATE = 8.0
	DEFAULT_PRIMARY_RANGE     = 760.0
	DEFAULT_PRIMARY_AMMO      = 30
)
